### Get Health
GET http://localhost:8080/actuator/health
Content-Type: application/json

### Retrieve Stats
POST http://localhost:8080/v1/weather/stats
Content-Type: application/json

{
    "metrics" : ["TEMPERATURE", "WINDSPEED"],
    "statType" : "AVG",
    "searchAllSensors" : true,
    "startDate" : "2023-06-01",
    "endDate" : "2023-06-09"
}


### Create a metric sample
POST http://localhost:8080/v1/weather/metrics
Content-Type: application/json

{
  "sampleId": 3,
  "sensorId": 2,
  "metrics": [{
    "metricType": "HUMIDITY",
    "metricValue": 14.0
  }, {
    "metricType": "RAINFALL",
    "metricValue": 18.0
  },
  {
    "metricType": "TEMPERATURE",
    "metricValue": 22.0
  },
  {
    "metricType": "WINDSPEED",
    "metricValue": 10.0
  }]
}

### Get a metric sample by its ID
GET http://localhost:8080/v1/weather/metrics/3
Content-Type: application/json

### Get all metric samples
GET http://localhost:8080/v1/weather/metrics
Content-Type: application/json

### Delete a metric sample by its ID
DELETE http://localhost:8080/v1/weather/metrics/2
Content-Type: application/json

### Update a metric sample
PATCH http://localhost:8080/v1/weather/metrics
Content-Type: application/json

{
  "sampleId": 1,
  "sensorId": 2,
  "metrics": [{
    "metricType": "HUMIDITY",
    "metricValue": 300.0
  }, {
    "metricType": "RAINFALL",
    "metricValue": 400.0
  }]
}