### Get Health
GET http://localhost:8080/actuator/health
Content-Type: application/json

### Retrieve Stats
POST http://localhost:8080/v1/weather/stats
Content-Type: application/json

{
    "sensorIds" : [2],
    "metrics" : ["TEMP", "WIND", "true"],
    "statType" : "AVG",
    "startDate" : "2023-05-01",
    "endDate" : "2023-06-30"
}


### Create a metric sample
POST http://localhost:8080/v1/weather/metrics
Content-Type: application/json

{
  "sampleId": 6,
  "sensorId": 2,
  "metrics": [{
    "metricName": "BLAH",
    "metricValue": 30.0
  }, {
    "metricName": "TEMP",
    "metricValue": 10
  }, {
    "metricName": "HUM",
    "metricValue": 15.0
  }, {
    "metricName": "RAIN",
    "metricValue": 10.0
  }]
}

### Get a metric sample by its ID
GET http://localhost:8080/v1/weather/metrics/1
Content-Type: application/json

### Get all metric samples
GET http://localhost:8080/v1/weather/metrics
Content-Type: application/json

### Delete a metric sample by its ID
DELETE http://localhost:8080/v1/weather/metrics/3
Content-Type: application/json

### Update a metric sample
PATCH http://localhost:8080/v1/weather/metrics
Content-Type: application/json

{
  "sampleId": 1,
  "sensorId": 2,
  "metrics": [{
    "metricName": "HUM",
    "metricValue": 30.0
  }, {
    "metricName": "RAIN",
    "metricValue": 40.0
  }]
}